// Code generated by ent, DO NOT EDIT.

package plane

const (
	// Label holds the string label denoting the plane type in the database.
	Label = "plane"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTailNumber holds the string denoting the tailnumber field in the database.
	FieldTailNumber = "tail_number"
	// Table holds the table name of the plane in the database.
	Table = "planes"
)

// Columns holds all SQL columns for plane fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTailNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
