// Code generated by ent, DO NOT EDIT.

package airline

const (
	// Label holds the string label denoting the airline type in the database.
	Label = "airline"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// Table holds the table name of the airline in the database.
	Table = "airlines"
)

// Columns holds all SQL columns for airline fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAlias,
	FieldCountry,
	FieldActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
