// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/site-tech/fake-data-service/ent/airline"
)

// AirlineCreate is the builder for creating a Airline entity.
type AirlineCreate struct {
	config
	mutation *AirlineMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *AirlineCreate) SetName(s string) *AirlineCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetAlias sets the "alias" field.
func (ac *AirlineCreate) SetAlias(s string) *AirlineCreate {
	ac.mutation.SetAlias(s)
	return ac
}

// SetCountry sets the "country" field.
func (ac *AirlineCreate) SetCountry(s string) *AirlineCreate {
	ac.mutation.SetCountry(s)
	return ac
}

// SetActive sets the "active" field.
func (ac *AirlineCreate) SetActive(b bool) *AirlineCreate {
	ac.mutation.SetActive(b)
	return ac
}

// SetID sets the "id" field.
func (ac *AirlineCreate) SetID(i int) *AirlineCreate {
	ac.mutation.SetID(i)
	return ac
}

// Mutation returns the AirlineMutation object of the builder.
func (ac *AirlineCreate) Mutation() *AirlineMutation {
	return ac.mutation
}

// Save creates the Airline in the database.
func (ac *AirlineCreate) Save(ctx context.Context) (*Airline, error) {
	return withHooks[*Airline, AirlineMutation](ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AirlineCreate) SaveX(ctx context.Context) *Airline {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AirlineCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AirlineCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AirlineCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Airline.name"`)}
	}
	if _, ok := ac.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Airline.alias"`)}
	}
	if _, ok := ac.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Airline.country"`)}
	}
	if _, ok := ac.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Airline.active"`)}
	}
	return nil
}

func (ac *AirlineCreate) sqlSave(ctx context.Context) (*Airline, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AirlineCreate) createSpec() (*Airline, *sqlgraph.CreateSpec) {
	var (
		_node = &Airline{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(airline.Table, sqlgraph.NewFieldSpec(airline.FieldID, field.TypeInt))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(airline.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.Alias(); ok {
		_spec.SetField(airline.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := ac.mutation.Country(); ok {
		_spec.SetField(airline.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := ac.mutation.Active(); ok {
		_spec.SetField(airline.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	return _node, _spec
}

// AirlineCreateBulk is the builder for creating many Airline entities in bulk.
type AirlineCreateBulk struct {
	config
	builders []*AirlineCreate
}

// Save creates the Airline entities in the database.
func (acb *AirlineCreateBulk) Save(ctx context.Context) ([]*Airline, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Airline, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AirlineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AirlineCreateBulk) SaveX(ctx context.Context) []*Airline {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AirlineCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AirlineCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
