// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/site-tech/fake-data-service/ent/airline"
	"github.com/site-tech/fake-data-service/ent/predicate"
)

// AirlineDelete is the builder for deleting a Airline entity.
type AirlineDelete struct {
	config
	hooks    []Hook
	mutation *AirlineMutation
}

// Where appends a list predicates to the AirlineDelete builder.
func (ad *AirlineDelete) Where(ps ...predicate.Airline) *AirlineDelete {
	ad.mutation.Where(ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AirlineDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, AirlineMutation](ctx, ad.sqlExec, ad.mutation, ad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AirlineDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AirlineDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(airline.Table, sqlgraph.NewFieldSpec(airline.FieldID, field.TypeInt))
	if ps := ad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ad.mutation.done = true
	return affected, err
}

// AirlineDeleteOne is the builder for deleting a single Airline entity.
type AirlineDeleteOne struct {
	ad *AirlineDelete
}

// Where appends a list predicates to the AirlineDelete builder.
func (ado *AirlineDeleteOne) Where(ps ...predicate.Airline) *AirlineDeleteOne {
	ado.ad.mutation.Where(ps...)
	return ado
}

// Exec executes the deletion query.
func (ado *AirlineDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{airline.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AirlineDeleteOne) ExecX(ctx context.Context) {
	if err := ado.Exec(ctx); err != nil {
		panic(err)
	}
}
