// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/site-tech/fake-data-service/ent/airport"
)

// AirportCreate is the builder for creating a Airport entity.
type AirportCreate struct {
	config
	mutation *AirportMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *AirportCreate) SetName(s string) *AirportCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ac *AirportCreate) SetNillableName(s *string) *AirportCreate {
	if s != nil {
		ac.SetName(*s)
	}
	return ac
}

// SetCity sets the "city" field.
func (ac *AirportCreate) SetCity(s string) *AirportCreate {
	ac.mutation.SetCity(s)
	return ac
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (ac *AirportCreate) SetNillableCity(s *string) *AirportCreate {
	if s != nil {
		ac.SetCity(*s)
	}
	return ac
}

// SetCountry sets the "country" field.
func (ac *AirportCreate) SetCountry(s string) *AirportCreate {
	ac.mutation.SetCountry(s)
	return ac
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (ac *AirportCreate) SetNillableCountry(s *string) *AirportCreate {
	if s != nil {
		ac.SetCountry(*s)
	}
	return ac
}

// SetIata sets the "iata" field.
func (ac *AirportCreate) SetIata(s string) *AirportCreate {
	ac.mutation.SetIata(s)
	return ac
}

// SetNillableIata sets the "iata" field if the given value is not nil.
func (ac *AirportCreate) SetNillableIata(s *string) *AirportCreate {
	if s != nil {
		ac.SetIata(*s)
	}
	return ac
}

// SetIcao sets the "icao" field.
func (ac *AirportCreate) SetIcao(s string) *AirportCreate {
	ac.mutation.SetIcao(s)
	return ac
}

// SetNillableIcao sets the "icao" field if the given value is not nil.
func (ac *AirportCreate) SetNillableIcao(s *string) *AirportCreate {
	if s != nil {
		ac.SetIcao(*s)
	}
	return ac
}

// SetLatitude sets the "latitude" field.
func (ac *AirportCreate) SetLatitude(f float64) *AirportCreate {
	ac.mutation.SetLatitude(f)
	return ac
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (ac *AirportCreate) SetNillableLatitude(f *float64) *AirportCreate {
	if f != nil {
		ac.SetLatitude(*f)
	}
	return ac
}

// SetLongitude sets the "longitude" field.
func (ac *AirportCreate) SetLongitude(f float64) *AirportCreate {
	ac.mutation.SetLongitude(f)
	return ac
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (ac *AirportCreate) SetNillableLongitude(f *float64) *AirportCreate {
	if f != nil {
		ac.SetLongitude(*f)
	}
	return ac
}

// SetAltitude sets the "altitude" field.
func (ac *AirportCreate) SetAltitude(i int) *AirportCreate {
	ac.mutation.SetAltitude(i)
	return ac
}

// SetNillableAltitude sets the "altitude" field if the given value is not nil.
func (ac *AirportCreate) SetNillableAltitude(i *int) *AirportCreate {
	if i != nil {
		ac.SetAltitude(*i)
	}
	return ac
}

// SetTimezone sets the "timezone" field.
func (ac *AirportCreate) SetTimezone(s string) *AirportCreate {
	ac.mutation.SetTimezone(s)
	return ac
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (ac *AirportCreate) SetNillableTimezone(s *string) *AirportCreate {
	if s != nil {
		ac.SetTimezone(*s)
	}
	return ac
}

// SetDst sets the "dst" field.
func (ac *AirportCreate) SetDst(s string) *AirportCreate {
	ac.mutation.SetDst(s)
	return ac
}

// SetNillableDst sets the "dst" field if the given value is not nil.
func (ac *AirportCreate) SetNillableDst(s *string) *AirportCreate {
	if s != nil {
		ac.SetDst(*s)
	}
	return ac
}

// SetTimezoneName sets the "timezoneName" field.
func (ac *AirportCreate) SetTimezoneName(s string) *AirportCreate {
	ac.mutation.SetTimezoneName(s)
	return ac
}

// SetNillableTimezoneName sets the "timezoneName" field if the given value is not nil.
func (ac *AirportCreate) SetNillableTimezoneName(s *string) *AirportCreate {
	if s != nil {
		ac.SetTimezoneName(*s)
	}
	return ac
}

// SetType sets the "type" field.
func (ac *AirportCreate) SetType(s string) *AirportCreate {
	ac.mutation.SetType(s)
	return ac
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ac *AirportCreate) SetNillableType(s *string) *AirportCreate {
	if s != nil {
		ac.SetType(*s)
	}
	return ac
}

// SetSource sets the "source" field.
func (ac *AirportCreate) SetSource(s string) *AirportCreate {
	ac.mutation.SetSource(s)
	return ac
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (ac *AirportCreate) SetNillableSource(s *string) *AirportCreate {
	if s != nil {
		ac.SetSource(*s)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AirportCreate) SetID(i int) *AirportCreate {
	ac.mutation.SetID(i)
	return ac
}

// Mutation returns the AirportMutation object of the builder.
func (ac *AirportCreate) Mutation() *AirportMutation {
	return ac.mutation
}

// Save creates the Airport in the database.
func (ac *AirportCreate) Save(ctx context.Context) (*Airport, error) {
	return withHooks[*Airport, AirportMutation](ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AirportCreate) SaveX(ctx context.Context) *Airport {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AirportCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AirportCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AirportCreate) check() error {
	return nil
}

func (ac *AirportCreate) sqlSave(ctx context.Context) (*Airport, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AirportCreate) createSpec() (*Airport, *sqlgraph.CreateSpec) {
	var (
		_node = &Airport{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(airport.Table, sqlgraph.NewFieldSpec(airport.FieldID, field.TypeInt))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(airport.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.City(); ok {
		_spec.SetField(airport.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := ac.mutation.Country(); ok {
		_spec.SetField(airport.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := ac.mutation.Iata(); ok {
		_spec.SetField(airport.FieldIata, field.TypeString, value)
		_node.Iata = value
	}
	if value, ok := ac.mutation.Icao(); ok {
		_spec.SetField(airport.FieldIcao, field.TypeString, value)
		_node.Icao = value
	}
	if value, ok := ac.mutation.Latitude(); ok {
		_spec.SetField(airport.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := ac.mutation.Longitude(); ok {
		_spec.SetField(airport.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := ac.mutation.Altitude(); ok {
		_spec.SetField(airport.FieldAltitude, field.TypeInt, value)
		_node.Altitude = value
	}
	if value, ok := ac.mutation.Timezone(); ok {
		_spec.SetField(airport.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := ac.mutation.Dst(); ok {
		_spec.SetField(airport.FieldDst, field.TypeString, value)
		_node.Dst = value
	}
	if value, ok := ac.mutation.TimezoneName(); ok {
		_spec.SetField(airport.FieldTimezoneName, field.TypeString, value)
		_node.TimezoneName = value
	}
	if value, ok := ac.mutation.GetType(); ok {
		_spec.SetField(airport.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := ac.mutation.Source(); ok {
		_spec.SetField(airport.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	return _node, _spec
}

// AirportCreateBulk is the builder for creating many Airport entities in bulk.
type AirportCreateBulk struct {
	config
	builders []*AirportCreate
}

// Save creates the Airport entities in the database.
func (acb *AirportCreateBulk) Save(ctx context.Context) ([]*Airport, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Airport, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AirportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AirportCreateBulk) SaveX(ctx context.Context) []*Airport {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AirportCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AirportCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
