// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/site-tech/fake-data-service/ent/plane"
)

// PlaneCreate is the builder for creating a Plane entity.
type PlaneCreate struct {
	config
	mutation *PlaneMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PlaneCreate) SetName(s string) *PlaneCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetTailNumber sets the "tailNumber" field.
func (pc *PlaneCreate) SetTailNumber(s string) *PlaneCreate {
	pc.mutation.SetTailNumber(s)
	return pc
}

// SetID sets the "id" field.
func (pc *PlaneCreate) SetID(i int) *PlaneCreate {
	pc.mutation.SetID(i)
	return pc
}

// Mutation returns the PlaneMutation object of the builder.
func (pc *PlaneCreate) Mutation() *PlaneMutation {
	return pc.mutation
}

// Save creates the Plane in the database.
func (pc *PlaneCreate) Save(ctx context.Context) (*Plane, error) {
	return withHooks[*Plane, PlaneMutation](ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PlaneCreate) SaveX(ctx context.Context) *Plane {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PlaneCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PlaneCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PlaneCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plane.name"`)}
	}
	if _, ok := pc.mutation.TailNumber(); !ok {
		return &ValidationError{Name: "tailNumber", err: errors.New(`ent: missing required field "Plane.tailNumber"`)}
	}
	return nil
}

func (pc *PlaneCreate) sqlSave(ctx context.Context) (*Plane, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PlaneCreate) createSpec() (*Plane, *sqlgraph.CreateSpec) {
	var (
		_node = &Plane{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(plane.Table, sqlgraph.NewFieldSpec(plane.FieldID, field.TypeInt))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(plane.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.TailNumber(); ok {
		_spec.SetField(plane.FieldTailNumber, field.TypeString, value)
		_node.TailNumber = value
	}
	return _node, _spec
}

// PlaneCreateBulk is the builder for creating many Plane entities in bulk.
type PlaneCreateBulk struct {
	config
	builders []*PlaneCreate
}

// Save creates the Plane entities in the database.
func (pcb *PlaneCreateBulk) Save(ctx context.Context) ([]*Plane, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Plane, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PlaneCreateBulk) SaveX(ctx context.Context) []*Plane {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PlaneCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PlaneCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
