// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/site-tech/fake-data-service/ent/route"
)

// RouteCreate is the builder for creating a Route entity.
type RouteCreate struct {
	config
	mutation *RouteMutation
	hooks    []Hook
}

// SetAirline sets the "airline" field.
func (rc *RouteCreate) SetAirline(s string) *RouteCreate {
	rc.mutation.SetAirline(s)
	return rc
}

// SetSourceAirportId sets the "sourceAirportId" field.
func (rc *RouteCreate) SetSourceAirportId(i int) *RouteCreate {
	rc.mutation.SetSourceAirportId(i)
	return rc
}

// SetDestinationAirportId sets the "destinationAirportId" field.
func (rc *RouteCreate) SetDestinationAirportId(i int) *RouteCreate {
	rc.mutation.SetDestinationAirportId(i)
	return rc
}

// SetNumberOfStops sets the "numberOfStops" field.
func (rc *RouteCreate) SetNumberOfStops(i int) *RouteCreate {
	rc.mutation.SetNumberOfStops(i)
	return rc
}

// SetID sets the "id" field.
func (rc *RouteCreate) SetID(i int) *RouteCreate {
	rc.mutation.SetID(i)
	return rc
}

// Mutation returns the RouteMutation object of the builder.
func (rc *RouteCreate) Mutation() *RouteMutation {
	return rc.mutation
}

// Save creates the Route in the database.
func (rc *RouteCreate) Save(ctx context.Context) (*Route, error) {
	return withHooks[*Route, RouteMutation](ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RouteCreate) SaveX(ctx context.Context) *Route {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RouteCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RouteCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RouteCreate) check() error {
	if _, ok := rc.mutation.Airline(); !ok {
		return &ValidationError{Name: "airline", err: errors.New(`ent: missing required field "Route.airline"`)}
	}
	if _, ok := rc.mutation.SourceAirportId(); !ok {
		return &ValidationError{Name: "sourceAirportId", err: errors.New(`ent: missing required field "Route.sourceAirportId"`)}
	}
	if _, ok := rc.mutation.DestinationAirportId(); !ok {
		return &ValidationError{Name: "destinationAirportId", err: errors.New(`ent: missing required field "Route.destinationAirportId"`)}
	}
	if _, ok := rc.mutation.NumberOfStops(); !ok {
		return &ValidationError{Name: "numberOfStops", err: errors.New(`ent: missing required field "Route.numberOfStops"`)}
	}
	return nil
}

func (rc *RouteCreate) sqlSave(ctx context.Context) (*Route, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RouteCreate) createSpec() (*Route, *sqlgraph.CreateSpec) {
	var (
		_node = &Route{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(route.Table, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.Airline(); ok {
		_spec.SetField(route.FieldAirline, field.TypeString, value)
		_node.Airline = value
	}
	if value, ok := rc.mutation.SourceAirportId(); ok {
		_spec.SetField(route.FieldSourceAirportId, field.TypeInt, value)
		_node.SourceAirportId = value
	}
	if value, ok := rc.mutation.DestinationAirportId(); ok {
		_spec.SetField(route.FieldDestinationAirportId, field.TypeInt, value)
		_node.DestinationAirportId = value
	}
	if value, ok := rc.mutation.NumberOfStops(); ok {
		_spec.SetField(route.FieldNumberOfStops, field.TypeInt, value)
		_node.NumberOfStops = value
	}
	return _node, _spec
}

// RouteCreateBulk is the builder for creating many Route entities in bulk.
type RouteCreateBulk struct {
	config
	builders []*RouteCreate
}

// Save creates the Route entities in the database.
func (rcb *RouteCreateBulk) Save(ctx context.Context) ([]*Route, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Route, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RouteCreateBulk) SaveX(ctx context.Context) []*Route {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RouteCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RouteCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
